# Generated by Django 5.0.3 on 2024-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_alter_dog_breed_alter_dog_name_alter_dog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dogs'),
        ),
    ]
