# Generated by Django 5.0.3 on 2024-03-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_alter_dog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=200, null=True, verbose_name='порода'),
        ),
    ]



