# Generated by Django 5.0.3 on 2024-03-23 11:12

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Dog = apps.get_model("shelter", "Dog")
    db_alias = schema_editor.connection.alias
    Dog.objects.using(db_alias).all().update(breed=None)


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_alter_dog_breed'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('description', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.breed'),
        ),
    ]
