# Generated by Django 5.0.3 on 2024-03-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_breed_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(),
        ),
    ]
